### PR TITLE
Add LLNL

### PR DESCRIPTION
**Pull request by wihobbs**
#37 on glassdoor's top 100 places to work.

### CODE REVIEW

**Comment by qc542** [comment]
This job requires US citizenship. Nothing wrong with the posting; just thought it would be nice to point that out.

**Comment by satyajeetkrjha** [comment]
Yeah .I got rejected in less than an hour .

**Comment by wihobbs** [comment]
Happy to add a note about that. Although to be fair work authorization (and in this case citizenship) is a pretty common requirement for most jobs in the US.

**Comment by Bryce-MW** [comment]
Pretty much all jobs require work authorization but there are a lot of non-citizens who don't need visa sponsorship like Canadians using TN status. It's mostly certain jobs in government or that interact with the government in certain ways that require citizenship specifically

**Pull request merged**
