### PR TITLE
Add Netflix

### PR DESCRIPTION
**Pull request by adityamulik**

### CODE REVIEW

**Comment by shengbo-ma** [comment]
It'd better to mention the position is for undergrad only.

**Comment by BBBmau** [comment]
@shengbo-ma yeah isn't that the point to include new grad undergrad positions?

**Comment by adityamulik** [comment]
I didn't notice it's undergrad, should I close it?

**Comment by shengbo-ma** [comment]
> I didn't notice it's undergrad, should I close it?

I think mentioned undergrad only in your PR should be good enough.

**Pull request merged**
