### PR TITLE
Update the current VMware item

### PR DESCRIPTION
**Pull request by Wu-Jingcheng**
Previous item name is sort of misleading. Feel like it's better to post the edu level requirement at the hyperlink. Potentially differentiated from the incoming all/master/PhD level jd link.

### CODE REVIEW

**Comment by danerwilliams** [comment]
I agree the verbiage is misleading but it should be differentiated in the notes section.

How about we update that to say something like "Bachelor's new grads" and then the notes for the grad school posting would be "masters / PhD new grads"

**Comment by blake-whitman** [comment]
SoFi posting requires a masters degree

**Comment by Wu-Jingcheng** [comment]
> I agree the verbiage is misleading but it should be differentiated in the notes section.
> 
> How about we update that to say something like "Bachelor's new grads" and then the notes for the grad school posting would be "masters / PhD new grads"

I think it works. One concern is that the first column may take up more space. Should work if you are okay with that.

**Comment by Adora2401** [comment]
> SoFi posting requires a masters degree

I have talked with one of Sofi employee, she said she had a conversion with HR and this job is not open for 2023 New Grad.

**Pull request closed without merging**
