### PR TITLE
Add Elsevier

### PR DESCRIPTION
**Pull request by qc542**

### CODE REVIEW

**Comment by thegeorgejoseph** [comment]
Link broken, points to an old unrelated job posting

**Comment by qc542** [comment]
> Link broken, points to an old unrelated job posting

It still works for me
Screenshot_20220903_132049

**Comment by thegeorgejoseph** [comment]
> > Link broken, points to an old unrelated job posting
> 
> It still works for me Screenshot_20220903_132049

image

**Comment by qc542** [comment]
> > > Link broken, points to an old unrelated job posting
> > 
> > 
> > It still works for me Screenshot_20220903_132049
> 
> image

I see. It was open when I created the PR.

**Pull request closed without merging**
