### PR TITLE
Add Airtable

### PR DESCRIPTION
**Pull request by jameszhang-a**
As per discussion in #143 , adding an Airtable link for the ability to sort/manage easily. I know from using the other repo from Pitt summer internship, the table gets very hard to read and go through as postings start coming in. 

Can add OP as owner of airtable if needed.

### CODE REVIEW

**Review by emenikeigwe — APPROVED** [review]

**Comment by jameszhang-a** [comment]
## [Airtable](https://airtable.com/shrS40XfZ5opJ3jLV)/[Submit](https://airtable.com/shrHLRT3pcaW8QBAv)

**Comment by jameszhang-a** [comment]
@coderQuad thoughts?

**Comment by danerwilliams** [comment]
Hey @jameszhang-a 👋 ! Sorry to get to this so late, had been unavailable for a few days. 

Appreciate the feedback, I think your concerns make a lot of sense and I would like to solve this pain point as well. 

My one question is, how are you planning to keep this Airtable in sync with the repo? We would like to keep this repo as the source of truth for job postings, and PR's to this repo should be where changes to the list are initiated. 

Apologies if this is a trivial question, I don't really use Airtable so I'm not terribly familiar with how it works.

**Comment by danerwilliams** [comment]
Following up on the previous comment, it looks to me that this Airtable not only adds an additional view of the job list, but also an additional space to submit jobs. 

With that model, I don't think it makes sense for maintainers. There should be one source of truth for submissions, PR's on this repo. 

If we have a script that regularly syncs the Airtable to this repo, then I think it's worthwhile to add a link to it in the Readme. Otherwise, we can not guarantee that they are mirrors. 

For that reason I'm closing this PR, but am open to merging this in as a link to just an Airtable (no submission form) if the aforementioned changes are implemented.

**Comment by emenikeigwe** [comment]
Can we revisit organization? It makes no sense to scroll all the way to the very bottom for the latest roles (if chronological order is still being prioritized).

It's not clear from the repo that the listings are even in a chronological ordering. It just looks messy.

**Comment by truongluan303** [comment]
I think a simple solution in case we don't want to scroll to the bottom for the latest role is to put the latest roles on top instead. So the latests will be on top and the oldest will be in the bottom.
I don't think alpha sorting will be a good way. Since it will make it super hard for people to know which one is recently added. And also, it will take the job posters more time to sort them as well.
Just a personal thought 😺

**Pull request closed without merging**
