### PR TITLE
Add Bloomberg

### PR DESCRIPTION
**Pull request by jercymat**

### CODE REVIEW

**Comment by t-khush** [comment]
heads up this is a recruiter link and not open to the public

**Comment by qc542** [comment]
So are we not supposed to use that link to apply?

**Comment by Bryce-MW** [comment]
It looks like a normal link to me? I didn't see anything in the description that made it look special

**Comment by t-khush** [comment]
Not sure if it's important. Just mentioned it because I don't believe this
link is accessible for everyone
 via the Bloomberg site

**Comment by qc542** [comment]
Right. I tried and couldn't find it by looking up the job title

**Comment by Bryce-MW** [comment]
Yea, that's interesting. I can't find it either. I don't know why this exists or where it is from but it did allow me to apply even though it can't be found with a search. I guess we'll see what the result of that is

**Comment by zyxing-Andrew** [comment]
I just saw somebody got a VO from this position.
Not sure if he applied it via a recruiter or not though...

**Comment by qc542** [comment]
> I just saw somebody got a VO from this position. Not sure if he applied it via a recruiter or not though...

You mean a verbal offer?

**Comment by zyxing-Andrew** [comment]
> > I just saw somebody got a VO from this position. Not sure if he applied it via a recruiter or not though...
> 
> You mean a verbal offer?

A virtual onsite call

**Comment by qc542** [comment]
I just got an invite to a phone interview. That page works.

**Comment by Bryce-MW** [comment]
I haven't heard anything back yet but if that's true then I think it is worth adding

**Comment by thinkfurther** [comment]
I got a video interview.

**Comment by qc542** [comment]
> I got a video interview.

Right. I thought it was a phone interview, but the confirmation email says it's actually video.

**Comment by NishanthPrajith** [comment]
I applied and still haven't gotten a anything from them.

**Comment by qc542** [comment]
> I applied and still haven't received anything from them. When did you apply @qc542 ?

Two days ago

**Comment by NishanthPrajith** [comment]
> Two days ago

Oh okay. I applied yesterday.

**Comment by NishanthPrajith** [comment]
Do you have an email address or something for the person who reached out to you? @qc542

**Comment by Bryce-MW** [comment]
Huh, I applied longer ago than that. Maybe they decided to ghost me

**Comment by NishanthPrajith** [comment]
It is strange that the job posting is not available on Bloomberg after a simple search. You literally have to google the job posting to find it. @Bryce-MW Honestly, I do not know, they seem to do this at random.

**Comment by Bryce-MW** [comment]
I'm pretty sure they ghosted me last year so maybe I'm just not the kind of person they are looking for

**Comment by danerwilliams** [comment]
In the past Bloomberg has created unique job links for events and such that are public but just not listed. That is probably what this is.

However, because this can be found via Google I'm going to merge it. If they don't want this to be used by the general public that's on them lol

**Comment by Bryce-MW** [comment]
Only took almost two weeks but now they have offered me a phone interview. So funny

**Pull request merged**
