### PR TITLE
Add Walmart Sam's Club

### PR DESCRIPTION
**Pull request by abhishek66642**

### CODE REVIEW

**Comment by Priyadarshanvijay** [comment]
SUS bro

**Comment by JustCasuallyJames** [comment]
When we are talking about new-grad positions, are we including positions that require 1+ years of experience?

**Comment by abhishek66642** [comment]
@JustCasuallyJames Yeah I only added it cause there are many Masters students following the repo and it might be relevant for them. Plus the qualifications state must be enrolled in Masters's graduating from December 2022 - August 2023.

**Comment by JustCasuallyJames** [comment]
> @JustCasuallyJames Yeah I only added it cause there are many Masters students following the repo and it might be relevant for them. Plus the qualifications state must be enrolled in Masters's graduating from December 2022 - August 2023.

That's fair! Thanks for posting this.

**Comment by danerwilliams** [comment]
Closing this because we're generally posting positions that are entirely entry level

**Comment by JustCasuallyJames** [comment]
I would probably mention that in the readme then if you wanted to specify specifically entry level new grad positions.

**Comment by abhishek66642** [comment]
@danerwilliams I have the link for the other Walmart Sam's Club role which requires 0-1 years experience, will post that shortly. Also agree with @JustCasuallyJames I think the README can be updated with that info.

**Pull request closed without merging**
