### PR TITLE
Add Leidos entry 

### PR DESCRIPTION
**Pull request by MackQian**

### CODE REVIEW

**Comment by WillWang1998** [comment]
You should update README.md instead of README-2022.md.

**Comment by MackQian** [comment]
done, thanks

**Comment by VaibhavvvBarot** [comment]
Requires U.S. citizenship

**Comment by MackQian** [comment]
Yes, I know, I put that in the description...

**Comment by lockwo** [comment]
Really, I don't see it??

**Comment by loot-gremlin** [comment]
https://github.com/VaibhavvvBarot why delete your comment?

**Comment by ufolux** [comment]
U.S. citizenship required

**Comment by danerwilliams** [comment]
Can you fix this diff? There are changes to the `README-2022` file

**Pull request closed without merging**
