### PR TITLE
Add DoorDash

### PR DESCRIPTION
**Pull request by voxuannguyen2001**

### CODE REVIEW

**Comment by qc542** [comment]
Do you know if they have a new grad role for the back end?

**Comment by Lu-Songyu** [comment]
Are we sure this is the role for new grad? I don't see any mention of grad date.

**Comment by sudheendrakatikar** [comment]
Job desc says 5+ YOE. Okay to delete.

**Comment by jhnlynn** [comment]
> Job desc says 5+ YOE. Okay to delete.

BS/MS/PhD OR 5+ yoe, worth a try tho

**Comment by voxuannguyen2001** [comment]
@qc542 I dont see any role for the backend

**Comment by voxuannguyen2001** [comment]
Job desc says BS/MS/PhD OR 5+ yoe, meaning experience is not required if you have had a bachelor degree. I think new grads can apply for this position

**Comment by jimmywutangclan** [comment]
No point in not trying, especially in this economy.

**Comment by WillWang1998** [comment]
I have already got rejected.

**Comment by Lu-Songyu** [comment]
> Regardless of whether or not we can apply, there's no point in not trying, especially in this economy.

Take it with a grain of salt, but I think the best approach is to wait for their NG to open and apply then. 
It may not hurt to apply for general jobs, but most likely they will reject you if you don't have full-time experience yet. Some company does freeze you for a certain period before looking at your resume again.

Just a second option.

**Comment by danerwilliams** [comment]
not a new grad position

**Pull request closed without merging**
