### PR TITLE
Add Dell Technologies

### PR DESCRIPTION
**Pull request by WillWang1998**

### CODE REVIEW

**Comment by qc542** [comment]
Do you have a link to the posting on Dell's own website? I tried to apply on WayUp, and it didn't direct me to Dell's website.

**Comment by WillWang1998** [comment]
> Do you have a link to the posting on Dell's own website? I tried to apply on WayUp, and it didn't direct me to Dell's website.

Visit https://jobs.dell.com/students-us and click "Explore Opportunities." After being redirected to the WayUp website, select  "Product & Engineering" in "Job Functions."

**Comment by qc542** [comment]
> > Do you have a link to the posting on Dell's own website? I tried to apply on WayUp, and it didn't direct me to Dell's website.
> 
> Visit https://jobs.dell.com/students-us and click "Explore Opportunities." After being redirected to the WayUp website, select "Product & Engineering" in "Job Functions."

I was able to apply on WayUp, but it didn't direct me to Dell's website, so the information I filled out wasn't as complete as if I had applied on Dell's website

**Comment by WillWang1998** [comment]
> > > Do you have a link to the posting on Dell's own website? I tried to apply on WayUp, and it didn't direct me to Dell's website.
> > 
> > 
> > Visit https://jobs.dell.com/students-us and click "Explore Opportunities." After being redirected to the WayUp website, select "Product & Engineering" in "Job Functions."
> 
> I was able to apply on WayUp, but it didn't direct me to Dell's website, so the information I filled out wasn't as complete as if I had applied on Dell's website

Maybe we can contact [university_relations@dell.com](mailto:university_relations@dell.com) for details.

**Comment by WillWang1998** [comment]
@qc542 
I got rejected just in one day. So I am not sure if it is available, or it is only for Bachelors.

**Comment by qc542** [comment]
> @qc542 I got rejected just in one day. So I am not sure if it is available, or it is only for Bachelors.

I got rejected too. My WayUp profile wasn't complete when I applied because I thought I was going to be redirected to Dell's website anyway. I added more info to my profile afterward, but that didn't help.

**Comment by WillWang1998** [comment]
I heard of other data points that there would be an auto-reject after applying via WayUp. So, I change the URL to the Workday one.

**Pull request merged**
