### PR TITLE
Add Esri

### PR DESCRIPTION
**Pull request by BBBmau**

### CODE REVIEW

**Comment by alexypdu** [comment]
Maybe append the entry to the end of the list?

**Comment by BBBmau** [comment]
@alexypdu Good Point, we should have it where the new ones are listed at the bottom. We should edit the PR directions to include that.

**Comment by qc542** [comment]
I went to the link, and it said the job is no longer available

**Comment by BBBmau** [comment]
@qc542 Wow, they must've removed it I was able to apply myself. I'll close it for now.

**Pull request closed without merging**
