### PR TITLE
Add Uber

### PR DESCRIPTION
**Pull request by rrgore**

### CODE REVIEW

**Comment by KnlnKS** [comment]
Splunk is not for new grad. It requires 6months of experience.

**Comment by rrgore** [comment]
Imo you can still apply for it. But, I'll remove it if you insist.

**Comment by chengyu2000311** [comment]
LOL, thanks for the info rrgore.

**Comment by KnlnKS** [comment]
Also the role has been updated to say Fall 2022 start, so it isn't even eligible for 2023 grads: https://jobs.jobvite.com/splunk/job/oumykfws

**Comment by chengyu2000311** [comment]
you are right KnlnKs, I take my word back

**Pull request merged**
