### PR TITLE
Add Visa

### PR DESCRIPTION
**Pull request by qc542**

### CODE REVIEW

**Comment by albertzed2000** [comment]
Does the application work for you guys? It gets stuck on the Gender select for me

**Comment by qc542** [comment]
> Does the application work for you guys? It gets stuck on the Gender select for me

I was able to submit the application

**Comment by thegeorgejoseph** [comment]
This seems to be an internship role

**Comment by qc542** [comment]
> This seems to be an internship role

It says "intern" underneath the title, but that seems like a mistake because one of the requirements is that you must graduate before next summer

**Comment by jeffuofa93** [comment]
> Does the application work for you guys? It gets stuck on the Gender select for me

Same here

**Comment by cezar-r** [comment]
This is random af but I’m 99% sure you were my TA for CSC 120 w Russ last
year.

**Comment by jeffuofa93** [comment]
> 



> This is random af but I’m 99% sure you were my TA for CSC 120 w Russ last year.

I definitely was lol shoot me a message on discord would love to catch up.

**Pull request merged**
