### PR TITLE
Add Disney - New York

### PR DESCRIPTION
**Pull request by mixemer**

### CODE REVIEW

**Comment by albertzed2000** [comment]
Link doesn't work

**Comment by mixemer** [comment]
No it does: https://jobs.disneycareers.com/job/-/-/391/39525514960

**Comment by BoxiangG** [comment]
I think it's already closed in the workday

**Comment by Caesar-Wei** [comment]
> No it does: https://jobs.disneycareers.com/job/-/-/391/39525514960

Now this link is closed

**Comment by mixemer** [comment]
Yes it got closed. Companies are fast lol they close.

**Pull request closed without merging**
