### PR TITLE
add twitch

### PR DESCRIPTION
**Pull request by aadityadhruv**
added twitch roles

### CODE REVIEW

**Comment by Hui606** [comment]
For ppl who don't know this, Amazon owns Twitch 100%. So if you have applied for a position at Amazon, no need to try this.

**Review by danerwilliams — CHANGES_REQUESTED** [review]
Please remove the changes to `README-2022.md`. That repo is only for archive purposes now. Also 1 listing per PR please

**Comment by qc542** [comment]
> Please remove the changes to `README-2022.md`. That repo is only for archive purposes now. Also 1 listing per PR please

We can only have one PR open at a time, so what should we do if we have multiple listings to add?

**Comment by danerwilliams** [comment]
You can just open multiple PR's. It's easier to review when there is 1 listing per PR.

**Comment by austinlhx** [comment]
> For ppl who don't know this, Amazon owns Twitch 100%. So if you have applied for a position at Amazon, no need to try this.

Not true at all. Though Amazon owns Twitch, their interview process is completely different. Applying to Amazon will not get you into Twitch. You need to apply directly to Twitch to be considered, same with Zoox, Audible and a few other Amazon subsidaries.

**Comment by jhnlynn** [comment]
> > For ppl who don't know this, Amazon owns Twitch 100%. So if you have applied for a position at Amazon, no need to try this.
> 
> 
> 
> Not true at all. Though Amazon owns Twitch, their interview process is completely different. Applying to Amazon will not get you into Twitch. You need to apply directly to Twitch to be considered, same with Zoox, Audible and a few other Amazon subsidiary.

Can you get hired by AWS through applying for Amazon

**Comment by aadityadhruv** [comment]
How do I remove the changes to `README-2022.md`? I trying a git reset, but that doesn't seem to do anything.

**Comment by danmoop** [comment]
Seems like this is not for new grad as they require to have a degree upon applying.

**Comment by qc542** [comment]
> Seems like this is not for new grad as they require to have a degree upon applying.

That could be true. I wish all companies could indicate the start date on the new grad job postings. At this time of the year some are hiring people that graduated this spring, and some are hiring those graduating in the winter or next spring. It's confusing when they don't say the start date on the posting.

**Comment by SwapnilKumbhar** [comment]
Out of curiosity: How do we know that this is a new-grad role? Is it only because there is no experience requirement?

I am asking this because most roles listed in the repository have "New grad" or "Early career" in their titles or descriptions.

**Comment by qc542** [comment]
> Out of curiosity: How do we know that this is a new-grad role? Is it only because there is no experience requirement?
> 
> I am asking this because most roles listed in the repository have "New grad" or "Early career" in their titles or descriptions.

A new grad role is any role that doesn't require any full-time experience, which is the case for this job posting

**Comment by SwapnilKumbhar** [comment]
^^ Got it. Thanks.

**Comment by WillWang1998** [comment]
It has already been closed.

**Comment by jimmywutangclan** [comment]
Damn they closed it before this was ever merged to the repo.

I gotta start checking the pull requests more.

**Comment by APatel2001** [comment]
Pretty sure that was an old link from last year that never got removed! I don't think Twitch new grad is out yet

**Pull request closed without merging**
