### PR TITLE
Sort list in alphabetical order

### PR DESCRIPTION
**Pull request by jameszhang-a**
I know we can `⌘ + f` but I think an ordered list is easier to go through.

### CODE REVIEW

**Comment by salil-khanna** [comment]
disagree, should be in date posted

**Comment by salil-khanna** [comment]
it's better to apply by date posted than alphabetical order since jobs are on a rolling basis ; you can't search by date posted

**Comment by jameszhang-a** [comment]
That's a good point, I wish we can sort by both date and name

**Comment by jameszhang-a** [comment]
Closing, see #144

**Pull request closed without merging**
