### PR TITLE
Add Radical Semiconductors

### PR DESCRIPTION
**Pull request by rushilsrivastava**

### CODE REVIEW

**Comment by VaibhavvvBarot** [comment]
Must be a U.S. citizen

**Comment by rushilsrivastava** [comment]
> Must be a U.S. citizen

Not quite, you just need to be able to work in the U.S. without sponsorship. From the posting directly:

> To comply with U.S. export control laws and regulations, including the Export Administration Regulations (EAR), you must be a U.S. citizen, lawful permanent resident of the U.S., protected individual as defined by 8 U.S.C. 1324b(a)(3), or eligible to obtain the required authorizations from the U.S. Department of State without sponsorship.

**Comment by thinkfurther** [comment]
You can add a comment as do not provide sponsorship

**Comment by rushilsrivastava** [comment]
> You can add a comment as do not provide sponsorship

Done.

**Comment by zbelateche** [comment]
Hi! It's Zach, from Radical. Just want to make something clear -- it's not sponsorship for work authorization, it's sponsorship for an export license. Candidates who are on OPT visas and the like are generally not eligible for to work on export controlled technologies.

"Must be a citizen or permanent resident" is probably the best tagline, as the edge cases to that are pretty rare.

Also, the name of the company is Radical Semiconductor, singular.

If you have any other questions, shoot me an email at zachbela@radicalsemiconductor.com :)

**Pull request merged**
