### PR TITLE
Add Ocient

### PR DESCRIPTION
**Pull request by cj81499**
I couldn't help myself but to tidy up the markdown and sort the list. As a result, it's probably easier to review this PR commit by commit.

If a maintainer would prefer I not make those changes (or make them separately), I'd be happy to revise.

### CODE REVIEW

**Comment by cj81499** [comment]
Fair enough. I'll remove the commit.

**Comment by c199898** [comment]
I couldn't find the 'Software Engineer I' position on the website. I can only see a similar one which is 'Software Engineer II'.

**Comment by cj81499** [comment]
I'll get in touch with someone from recruiting about this.

I'll also change this to a draft, and will reopen when we've got that worked out!

**Comment by danerwilliams** [comment]
Hey @cj81499 👋 ,

Thanks so much for contributing! 

Sorry for the very overdue review of this. It's been busy for a few weeks and am just now getting through the backlog.

We're working on a platform right now that will provide access to this data on a site that can be filtered and sorted since there are limitations with markdown. 

As far as cleaning up the Markdown, this is definitely worth while. We maintain this pretty lazily and don't enforce any formatting (I've been meaning to implement some github actions for this). 

Would you mind splitting this PR in two? One to add Ocient, and another to clean up formatting? Also what formatter are you using? Prettier?

**Comment by cj81499** [comment]
Thanks for the reminder about this. I checked back in with recruiting and the position(s) have filled (for now), so I'm closing the PR.

iirc, I sorted using VSCode's "Sort Lines Ascending" command and cleaned up by hand + regex to find extraneous whitespace. It's obviously quite stale now though...

**Pull request closed without merging**
