### PR TITLE
Add Apple Inc

### PR DESCRIPTION
**Pull request by adityamulik**

### CODE REVIEW

**Comment by danerwilliams** [comment]
Please follow the PR format

**Comment by satyajeetkrjha** [comment]
Is this for grad 2023? I don't see this written anywhere.

**Comment by emenikeigwe** [comment]
Early career is different from new grad. I think that’s where the
discrepancy is coming from.

**Comment by danerwilliams** [comment]
This doesn't appear to be Apple's new grad listing as @emenikeigwe pointed out. Early career in past years has been distinct for them.

**Pull request closed without merging**
