### PR TITLE
Add JPMorgan Chase

### PR DESCRIPTION
**Pull request by WillWang1998**

### CODE REVIEW

**Comment by rahmankeenan** [comment]
They dont support CPT and OPT

**Comment by rahmankeenan** [comment]
image

**Comment by WillWang1998** [comment]
> image

I have indicated it in the notes. Because this repo is also for US-citizen new grads, I still created this pr.

**Comment by rahmankeenan** [comment]
Oh sorry i didnt checked that

**Comment by WillWang1998** [comment]
> Oh sorry i didnt checked that

nvm

**Pull request merged**
