### PR TITLE
Add Visa information about Capital One's position

### PR DESCRIPTION
**Pull request by zhu-yifang**
Capital One's position doesn't sponsor working visas, and you get rejected immediately if you declare sponsorship need in the application.

### CODE REVIEW

**Comment by zhu-yifang** [comment]
Also, can you make the list alphabetically ordered?

**Comment by Techming** [comment]
@danerwilliams Why did you close all the visa-related issues without any explanation? Isn't that part of the key information for the job listing? Or could you at least explain the reason behind your decision?

**Comment by ducdoan510** [comment]
@zhu-yifang I think alphabetically ordered listing is not necessary because people who view the list frequently want to know what are the new listings since they last visited and I think a good way to do that is to just append new ones to the existing list.
@Techming not sure what is the reason @danerwilliams closed the PR but I think visa information is good to have but not really needed. Sure it is key information but applicants should at least read the JD before applying. Otherwise if we try to include all the key info, this repo might end up pasting the whole JD into each listing.

**Comment by KnlnKS** [comment]
@zhu-yifang I actually had the same question, and created a pr to implement a simple website with alphabetic sorting. However, the maintainers informed me a site with such functionality and more is in the works.

**Comment by zhu-yifang** [comment]
> @zhu-yifang I think alphabetically ordered listing is not necessary because people who view the list frequently want to know what are the new listings since they last visited and I think a good way to do that is to just append new ones to the existing list.
> @Techming not sure what is the reason @danerwilliams closed the PR but I think visa information is good to have but not really needed. Sure it is key information but applicants should at least read the JD before applying. Otherwise if we try to include all the key info, this repo might end up pasting the whole JD into each listing.

Actually I think visa information is not only good but essential for foreigners.

**Comment by zhu-yifang** [comment]
> @zhu-yifang I actually had the same question, and created a pr to implement a simple website with alphabetic sorting. However, the maintainers informed me a site with such functionality and more is in the works. 

What is the site?

**Comment by danerwilliams** [comment]
We have stated on multiple occasions that we do not plan to include visa information at this time in the notes. That section is more for information about the type of job listing like SDE versus dev ops and to note if the company has other postings.

**Comment by danerwilliams** [comment]
That being said, the more detailed site we are working on we are researching an effective way to include this information as it is highly requested.

**Comment by Techming** [comment]
That reseasoning makes sense to me, but I would suggest that the maintainer should put those ideas (why we don't want visa information included and what's the undergoing plan for the more detailed site) at the top level of the README so that 1. contributors won't need to make useless extra effort to open PR 2. communication is more clear and efficient and people won't need to ask questions multiple times and multiple places.

Thanks for all your efforts in making these happen.

**Pull request closed without merging**
