### PR TITLE
Add Snowflake

### PR DESCRIPTION
**Pull request by BBBmau**

### CODE REVIEW

**Comment by qc542** [comment]
If you click on "apply" on the job page, it'll say the position is closed

**Comment by BBBmau** [comment]
Wow good catch, the Toronto position does work though. I'll edit out San Mateo for now.

**Comment by zxuanxu** [comment]
Also, this job is for 2022 graduates, not 2023.

**Comment by BBBmau** [comment]
I'll close since it's for 2022 Graduates

**Pull request closed without merging**
