### PR TITLE
Add Twilio

### PR DESCRIPTION
**Pull request by WillWang1998**

### CODE REVIEW

**Comment by WillWang1998** [comment]
I applied on 9/12 and got rejected today.

**Comment by cosmicRover** [comment]
> I applied on 9/12 and got rejected today.

did you at-least get an OA?

**Comment by WillWang1998** [comment]
> > I applied on 9/12 and got rejected today.
> 
> did you at-least get an OA?

No. And since they are laying off and didn't give any return offer for interns, I don't think they will hire any NG, at least for NG who will graduate this December.

**Comment by cosmicRover** [comment]
> > > I applied on 9/12 and got rejected today.
> > 
> > 
> > did you at-least get an OA?
> 
> No. And since they are laying off and didn't give any return offer for interns, I don't think they will hire any NG, at least for NG who will graduate this December.

RIPP

**Pull request merged**
