### PR TITLE
Close Neeva

### PR DESCRIPTION
**Pull request by rohit-badugu**
Headcount full

### CODE REVIEW

**Comment by qc542** [comment]
Hi @rohit-badugu , did a recruiter tell you their headcount is full? I scheduled a final interview with them, and they canceled it at the last minute and said they would reschedule it later. I haven't heard anything since.

**Comment by jmmanley** [comment]
Yes, I received this email:

> Thank you for applying for Neeva's Software Engineer, New Grad, 2023 position. We are reaching out today to inform you that the headcount for this position has been filled.
> 
> That being said, if you're currently a PhD or Masters student with two or more years of professional experience working on projects directly using Machine Learning/Natural Language Processing/Large Language Models, we'd love for you to reapply [for this role](https://jobs.lever.co/neeva/462d719a-3b71-4da1-900a-c87ab3f3b1a2).
> 
> We appreciate the time you took to fill out our application and would like to stay in touch! Please keep an eye on our [jobs page](https://neeva.com/jobs).
>  
> We wish you the best of luck on your search! 
> -- The Neeva Team

**Comment by chayank-neu** [comment]
Same here. I received the same.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by qc542** [comment]
> Yes, I received this email:
> 
> > Thank you for applying for Neeva's Software Engineer, New Grad, 2023 position. We are reaching out today to inform you that the headcount for this position has been filled.
> > That being said, if you're currently a PhD or Masters student with two or more years of professional experience working on projects directly using Machine Learning/Natural Language Processing/Large Language Models, we'd love for you to reapply [for this role](https://jobs.lever.co/neeva/462d719a-3b71-4da1-900a-c87ab3f3b1a2).
> > We appreciate the time you took to fill out our application and would like to stay in touch! Please keep an eye on our [jobs page](https://neeva.com/jobs).
> > We wish you the best of luck on your search!
> > -- The Neeva Team

I didn't get that email. What stage of the process were you in when you got it?

**Comment by max-heller** [comment]
Had a final round scheduled next week and just got an email saying headcount is full

**Pull request merged**
